- name: Manage Awesome website
  hosts: all
  vars:
    index_title: Awesome website
    index_content: Welcome to Ansible Automates !
    index_foot: Hosted on {{ ansible_hostname }}

  tasks:
  - when: command == 'deploy'
    block:
      - name: httpd package is present
        yum:
          name: httpd
